server.port=8081
spring.profiles.active=dev
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:mysql://localhost:3306/shopstack?createDatabaseIfNotExist=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

# Razorpay Credentials
razorpay.key.id=rzp_test_yourKeyId
razorpay.key.secret=yourSecretKey